"""empty message

Revision ID: 39f30d6f4bf4
Revises: a81ce728be3e
Create Date: 2022-10-25 20:59:56.175268

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '39f30d6f4bf4'
down_revision = 'a81ce728be3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('last_name', sa.String(length=255), nullable=True))
    op.add_column('auth_user', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.drop_constraint('auth_user_email_key', 'auth_user', type_='unique')
    op.create_index(op.f('ix_auth_user_email'), 'auth_user', ['email'], unique=True)
    op.create_index(op.f('ix_auth_user_last_name'), 'auth_user', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_user_last_name'), table_name='auth_user')
    op.drop_index(op.f('ix_auth_user_email'), table_name='auth_user')
    op.create_unique_constraint('auth_user_email_key', 'auth_user', ['email'])
    op.drop_column('auth_user', 'first_name')
    op.drop_column('auth_user', 'last_name')
    # ### end Alembic commands ###